<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Test UI Tool - Option 1</title>
		<link rel="shortcut icon" href="#" />
		<link rel="stylesheet" href="main.css">
	</head>
	<body>
    	<div id="main">
        	<div id="menu">
        		<div id="menuHead">
        			<div id="title">
	        			<p>Test Tool</p>
	        		</div>
	        		<div id="icon">
	        			<img title="Title" src="images/face-icon.png" height="20px" style="margin: 0;" />
	        		</div>
        		</div>
        		<div id="menuItems">
            		<p><a href="home">Home</a></p>
            		<p><a href="option1">Option I</a></p> 
            		<p><a href="option2">Option II</a></p> 
            		<p><a href="option3">Option III</a></p> 
            		<p><a href="option4">Option IV</a></p>
            		<hr />
            		<p class="disabled">Login</p>
            	</div>
       		</div>
        	<div id="content">
        		<div id="contentHead">
        			Login
        		</div>
        		<div id="contentBody">
           			Right Login
           		</div>
        	</div>
    	</div>
	</body>
</html>