<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>REST API UI Tool</title>
		<link rel="shortcut icon" href="#" />
		<link rel="stylesheet" href="main.css">
		<script type="text/javascript" src="pages.js"></script>
	</head>
	<body onload="init(-1)">
    	<div id="main">
        	<div id="menu">
        		<div id="menuHead">
        			<div id="title">
	        			<p>Test Tool</p>
	        		</div>
	        		<div id="icon">
	        			<img title="Title" src="images/face-icon.png" height="20px" style="margin: 0;" />
	        		</div>
        		</div>
        		<div id="menuItems">
            	</div>
       		</div>
        	<div id="content">
        		<div id="contentHead">
        			<div id="contentTitle">
        			</div>
        		</div>
        		<div id="contentBody">
        			<div id="contentBHead">
	           			See below the APIs supported by this UI.
        			</div>
        			<div id="contentCards">
      		  			<ul id="cards" class="card-container">
  						</ul>
        			</div>
           		</div>
        	</div>
    	</div>
	</body>
</html>