<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Test UI Tool</title>
		<link rel="stylesheet" href="main.css">
	</head>
	<body>
    	<div id="main">
        	<div id="menu">
        		<div id="menuHead">
        			<div id="title">
	        			<p>Test Tool</p>
	        		</div>
	        		<div id="icon">
	        			<img title="" src="images/face-icon-off.png" height="20px" style="margin: 0;" />
	        		</div>
        		</div>
        		<div id="menuItems">
            		<p class="disabled">Home</p>
            		<p><a href="option1.html">Option 1</a></p> 
            		<p><a href="option2.html">Option 2</a></p> 
            		<p><a href="option3.html">Option 3</a></p> 
            		<p><a href="option4.html">Option 4</a></p>
            		<hr />
            		<p><a href="login.html">Login</a></p>
            	</div>
       		</div>
        	<div id="content">
        		<div id="contentHead">
        			Home
        		</div>
        		<div id="contentBody">
        			<div id="contentBHead">
	           			Right Home.
        			</div>
        			<div id="contentCards">
      		  			<ul class="card-container">
  							<li>
        						<div class="card">
        				 			<div class="cardHeader">
        				 				Option 1
        				 			</div>
  									<div class="container">
    									<p>This option is an example of what may be achieved.</p>
  									</div>
  									<div class="cardFooter">
	  									<button onclick="window.location.href='option1.html'; return false;" type="button">Option 1</button>
  									</div>
								</div>
							</li>
							<li>
        						<div class="card">
        				 			<div class="cardHeader">
        				 				Option 2
        				 			</div>
  									<div class="container">
    									<p>This option is an example of what may be achieved.</p>
  									</div>
  									<div class="cardFooter">
	  									<button onclick="window.location.href='option2.html'; return false;" type="button">Option 2</button>
  									</div>
								</div>
  							</li>
							<li>
        						<div class="card">
        				 			<div class="cardHeader">
        				 				Option 3
        				 			</div>
  									<div class="container">
    									<p>This option is an example of what may be achieved.</p>
  									</div>
  									<div class="cardFooter">
	  									<button onclick="window.location.href='option3.html'; return false;" type="button">Option 3</button>
  									</div>
								</div>
  							</li>
							<li>
        						<div class="card">
        				 			<div class="cardHeader">
        				 				Option 4
        				 			</div>
  									<div class="container">
    									<p>This option is an example of what may be achieved.</p>
  									</div>
  									<div class="cardFooter">
	  									<button onclick="window.location.href='option4.html'; return false;" type="button">Option 4</button>
  									</div>
								</div>
  							</li>
  						</ul>
        			</div>
           		</div>
        	</div>
    	</div>
	</body>
</html>